Add some descriptions into README *Impl classes have been declared as final and package-private, no one should know its existence but Custom Plugin maintainers Add HeadersPropagatorFactory
* Da risolvere

<<
claudio@claudio-N14xWU:~/Downloads/workspace/custom-plugin-java/CRUD-docker$ docker-compose up
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will b$

To deploy your application across the swarm, use `docker stack deploy`.

Pulling crud-service (nexus.mia-platform.eu/core/crud-service:0.11.0)...
ERROR: Get https://nexus.mia-platform.eu/v2/core/crud-service/manifests/0.11.0: no basic auth credenti$
>>